# Generated by Django 4.2.5 on 2023-12-09 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0002_boleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('entregado', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('cantidad_recibida', models.IntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('orden_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.ordenpedido')),
            ],
        ),
    ]
